---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sas-natural-language-understanding
spec:
  host: sas-natural-language-understanding
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: sas-ingress-istio
          path: /naturalLanguageUnderstanding/
          ttl: 0s

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    sas.com/kustomize-base: base
  labels:
    app.kubernetes.io/name: sas-natural-language-understanding
    sas.com/admin: namespace
  name: sas-natural-language-understanding
spec:
  gateways:
  - public-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /naturalLanguageUnderstanding
    - uri:
        prefix: /naturalLanguageUnderstanding/
    route:
    - destination:
        host: sas-natural-language-understanding
    timeout: 600s

