apiVersion: builtin
kind: PatchTransformer
metadata:
  name: crunchy-add-image-secrets-sa-3
patch: |-
  - op: replace
    path: /imagePullSecrets
    value:
    - name: sas-image-pull-secrets
target:
  kind: ServiceAccount
  name: pgo.*
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: crunchy-add-image-secrets-sa-4
patch: |-
  - op: replace
    path: /imagePullSecrets
    value:
    - name: sas-image-pull-secrets
target:
  kind: ServiceAccount
  name: postgres-operator
  version: v1
---