CREATE TABLE IF NOT EXISTS TESTBDF ( 
extraction_id String,
code_riad String,
code_riad_temp String,
lei String,
siren String,
siren_fictif String,
cib String,
code_opc String,
code_ot String,
code_ncb String,
code_amf String,
code_org_int String,
code_nis String,
identifiant_rci String,
identifiant_rna String,
code_bic String,
identifiant_etranger String,
type_identifiant_etranger String,
identifiant_head_office String,
identifiant_immediate_parent String,
identifiant_ultimate_parent String,
date_debut_entite date,
date_fin_entite date,
denomination String,
adresse_ligne1 String,
adresse_ligne2 String,
adresse_ligne3 String,
adresse_ligne4 String,
code_postal String,
ville String,
code_nuts String,
pays String,
forme_juridique String,
code_secteur String,
code_sous_secteur String,
code_nace String,
statut_procedure_judiciaire String,
date_statut_procedure_judiciaire String,
taille_entreprise String,
date_taille_entreprise date,
nombre_employes bigint,
total_bilan decimal(20,2),
chiffre_affaires decimal(20,2),
norme_comptable_indiv String,
actif String
) 
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
