apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: annotations-transformer
annotations:
  sas.com/component-name: sas-natural-language-conversations
fieldSpecs:
- path: metadata/annotations
  create: true