
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    sas.com/kustomize-base: base
    sas.com/registry-providers: jobExecution-provider-Compute,dataSources-provider-Compute,dataTables-provider-Compute,rowSets-provider-Compute,jobExecution-provider,dataSources-provider,dataTables-provider,rowSets-provider
    sas.com/registry-sync: default
    sas.com/registry-tags: proxy
  labels:
    app.kubernetes.io/name: sas-compute
    sas.com/admin: namespace
  name: sas-compute
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-compute
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sas.com/certificate-file-format: jks
    sas.com/kustomize-base: spring
    sas.com/pod-uses-liveness-probe: http
    sas.com/pod-uses-readiness-probe: http
    sas.com/pod-uses-startup-probe: http
    sidecar.istio.io/proxyCPU: 15m
    sidecar.istio.io/proxyMemory: 115Mi
  labels:
    app.kubernetes.io/name: sas-compute
    sas.com/admin: namespace
    sas.com/deployment-base: spring
    workload.sas.com/class: stateless
  name: sas-compute
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-compute
  template:
    metadata:
      annotations:
        prometheus.io/path: /internal/metrics
        prometheus.io/port: "10445"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        sas.com/certificate-file-format: jks
        sas.com/kustomize-base: spring
        sas.com/pod-uses-liveness-probe: http
        sas.com/pod-uses-readiness-probe: http
        sas.com/pod-uses-startup-probe: http
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        sidecar.istio.io/proxyCPU: 15m
        sidecar.istio.io/proxyMemory: 115Mi
      labels:
        app: sas-compute
        app.kubernetes.io/name: sas-compute
        workload.sas.com/class: stateless
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
                - connect
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sas-compute
              topologyKey: kubernetes.io/hostname
            weight: 100
      automountServiceAccountToken: false
      containers:
      - env:
        - name: SAS_K8S_DEPLOYMENT_NAME
          value: sas-compute
        envFrom:
        - configMapRef:
            name: sas-java-config
        - configMapRef:
            name: sas-shared-config
        - secretRef:
            name: sas-consul-client
        - configMapRef:
            name: sas-spring-management-config
        image: sas-compute
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/live
            port: http-internal
            scheme: HTTP
          periodSeconds: 10
        name: sas-compute
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 10445
          name: http-internal
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/ready
            port: http-internal
            scheme: HTTP
          periodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 650M
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 180
          httpGet:
            path: /internal/live
            port: http-internal
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /opt/sas/viya/config/tmp
          name: tmp
      imagePullSecrets: []
      securityContext:
        runAsNonRoot: true
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      volumes:
      - emptyDir: {}
        name: tmp

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: base
  name: sas-compute
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-compute

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    sas.com/ha-class: centralized
    sas.com/kustomize-base: spring
  name: sas-compute
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sas-compute

---
apiVersion: v1
kind: PodTemplate
metadata:
  annotations:
    launcher.sas.com/jobContainerName: sas-programming-environment
    sas.com/certificate-file-format: pem
    sas.com/config-init-mode: initcontainer
    sas.com/kustomize-base: podtemplate
    sas.com/sas-access-config: "true"
  labels:
    sas.com/template-intent: sas-launcher
    workload.sas.com/class: compute
  name: sas-compute-job-config
template:
  metadata:
    annotations:
      sas.com/certificate-file-format: pem
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
      sidecar.istio.io/inject: "false"
    labels:
      launcher.sas.com/job-type: compute-server
  spec:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: In
              values:
              - compute
          weight: 100
        - preference:
            matchExpressions:
            - key: workload.sas.com/class
              operator: NotIn
              values:
              - cas
              - connect
              - stateless
              - stateful
          weight: 50
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: NotIn
              values:
              - system
    containers:
    - env:
      - name: SAS_LICENSE
        valueFrom:
          secretKeyRef:
            key: SAS_LICENSE
            name: sas-license
      - name: SAS_URL_SERVICE_TEMPLATE
        valueFrom:
          configMapKeyRef:
            key: SAS_URL_SERVICE_TEMPLATE
            name: sas-shared-config
      - name: SASCLOUDNATIVE
        value: "1"
      - name: LAUNCH_AS_JOB
        value: "true"
      - name: COMPUTESERVER_USER_CONFIG
        value: /config
      - name: COMPUTESERVER_VAR_PATH
        value: /viya
      envFrom:
      - configMapRef:
          name: sas-access-config
      - configMapRef:
          name: sas-deployment-metadata
      - configMapRef:
          name: sas-compute-server-config
      - configMapRef:
          name: sas-shared-config
      image: sas-programming-environment
      name: sas-programming-environment
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
      volumeMounts:
      - mountPath: /tmp
        name: tmp
      - mountPath: /sasuser
        name: sasuser
      - mountPath: /sashelp
        name: sashelp
      - mountPath: /config
        name: config
      - mountPath: /viya
        name: viya
    imagePullSecrets: []
    initContainers:
    - envFrom:
      - configMapRef:
          name: sas-go-config
      - configMapRef:
          name: sas-shared-config
      - secretRef:
          name: sas-consul-client
      - configMapRef:
          name: sas-compute-server-config
      image: sas-config-init
      name: sas-config-init
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: true
      volumeMounts:
      - mountPath: /tmp
        name: config-init-tmp
      - mountPath: /config
        name: config
    securityContext:
      runAsNonRoot: true
    tolerations:
    - effect: NoSchedule
      key: workload.sas.com/class
      operator: Equal
      value: compute
    volumes:
    - emptyDir: {}
      name: tmp
    - emptyDir: {}
      name: config-init-tmp
    - emptyDir: {}
      name: sasuser
    - emptyDir: {}
      name: sashelp
    - emptyDir: {}
      name: config
    - emptyDir: {}
      name: viya
