/******************************************************************************/
/* DEMO HMEQ : SAS Random Forest training code and model registering in the   */
/* central model repository of SAS Viya                                       */
/******************************************************************************/

%let viyahost=frasepviya35smp.cloud.com

options cashost=&viyahost casport=5570;
cas _CAS_PUBLIC_;

caslib _ALL_ assign;

/******************************************************************************/
/* Create a Forest analytic store model and store the model in a  CAS table.  */
/******************************************************************************/

proc forest data=public.hmeq_train 
     seed=12345 loh=0 binmethod=QUANTILE maxbranch=2 
     assignmissing=USEINSEARCH minuseinsearch=1
     ntrees=100
     maxdepth=20
     inbagfraction=0.6
     minleafsize=5
     numbin=50
     vote=PROBABILITY printtarget;
  target BAD / level=nominal;
  input LOAN MORTDUE VALUE YOJ DEROG DELINQ CLAGE CLNO DEBTINC / level=interval;
  input REASON JOB NINQ / level=nominal;
  savestate rstore=public.state;
run;

/******************************************************************/
/* REGISTER NEW TRAINED MODEL IN THE CENTRALIZED MODEL REPOSITORY */
/* through MACRO (coded or generated by graphical task)           */
/******************************************************************/
/* Empty Project HMEQ_Modeling must have been created in          */
/* model manager  */

%mm_get_project_id(
    projectnm=%nrstr(HMEQ_Modeling),
    idvar=myProjID,
    servernm=&servernm
);

%mm_import_astore_model(
	locationID=&myProjID,
	isfolder=N, 
	modelname=%nrstr(Forest Astore SAS Studio on HMEQ TRAIN),  
	modeldesc=Forest,	
	target=BAD,  
	targetlevel=binary,  
	projectVersion=%str(new), 
	rstore=public.state /* Specify the binary state of the model produced in the training phase */, 
	miningAlgorithm=%nrstr(forest), 
	miningFunction=classification,  
	pkgfolder=/opt/demo/mmpkgs);

cas _CAS_PUBLIC_ terminate;

/******************************************************************/
