apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sas-cas-operator
  labels:
    sas.com/admin: cluster-wide
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
