apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role.yaml
- cluster-role-binding.yaml

configurations:
- kustomizeconfig.yaml

# Pull the namespace of the ClusterRoleBinding into a var
#  to make the clusterrolebinding name unique
vars:
- name: BINDING_NAMESPACE
  objref:
    kind: ClusterRoleBinding
    name: sas-cas-operator
    apiVersion: rbac.authorization.k8s.io/v1
  fieldref:
    fieldpath: subjects[0].namespace

transformers:
- update-cluster-role-binding-name.yaml
