---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.sas.com/class: stateless
    name: sas-crunchy-data-pgadmin
    vendor: crunchydata
  name: sas-crunchy-data-pgadmin
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/duname: sas-crunchy-data-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sas-crunchy-data-pgadmin
      vendor: crunchydata
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.sas.com/class: stateless
        name: sas-crunchy-data-pgadmin
        vendor: crunchydata
      annotations:
        sas.com/certificate-file-format: pem
        sas.com/duname: sas-crunchy-data-pgadmin
    spec:
      imagePullSecrets: []
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateless
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateful
                - connect
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
      containers:
      - env:
        - name: PGADMIN_SETUP_EMAIL
          valueFrom:
            secretKeyRef:
              key: setupemail
              name: sas-crunchy-data-pgadmin-secrets
        - name: PGADMIN_SETUP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: setuppassword
              name: sas-crunchy-data-pgadmin-secrets
        - name: SERVER_PORT
          value: "5050"
        - name: SERVER_PATH
          value: "/pgadmin"
        - name: ENABLE_TLS
          value: "false"
        envFrom: []
        image: sas-crunchy-data-pgadmin
        imagePullPolicy: IfNotPresent
        name: sas-crunchy-data-pgadmin
        ports:
        - containerPort: 5050
          name: pgadmin
          protocol: TCP
        volumeMounts: []
      volumes: []
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
---
apiVersion: v1
kind: Service
metadata:
  name: sas-crunchy-data-pgadmin
spec:
  ports:
    - name: pgadmin
      port: 5050
      protocol: TCP
      targetPort: pgadmin
  type: ClusterIP
---