apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-model-repository-python-transformer
patch: |-
  # Add Python volume
  - op: add
    path: /spec/template/spec/volumes/-
    value: { name: python-volume, {{ VOLUME-ATTRIBUTES }} }

  # Add mount path for Python
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: python-volume
      mountPath: /python
      readOnly: true

  # Add restore job parameters
  - op: add
    path: /spec/template/spec/containers/0/envFrom/-
    value:
      configMapRef:
        name: sas-restore-job-parameters
target:
  group: apps
  kind: Deployment
  name: sas-model-repository
  version: v1