apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: benchmark-sas-crunchy-data-postgres
    pgo-benchmark: "true"
    pgouser: pgoadmin
    vendor: crunchydata
  name: benchmark-sas-crunchy-data-postgres
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: benchmark-sas-crunchy-data-postgres
        pg-cluster: sas-crunchy-data-postgres
        pgo-benchmark: "true"
        vendor: crunchydata
      name: benchmark-sas-crunchy-data-postgres
    spec:
      containers:
      - env:
        - name: PG_DATABASE
          value: {{ DATABASE_NAME }}
        - name: PG_HOSTNAME
          value: sas-crunchy-data-postgres
        - name: PG_PORT
          value: "5432"
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: sas-crunchy-data-postgres-postgres-secret
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: sas-crunchy-data-postgres-postgres-secret
        - name: PGBENCH_BENCHMARK_OPTS
        - name: PGBENCH_INIT_OPTS
        - name: PGBENCH_CLIENTS
          value: "1"
        - name: PGBENCH_JOBS
          value: "1"
        - name: PGBENCH_SCALE
          value: "1"
        - name: PGBENCH_TRANSACTIONS
          value: "1"
        image: sas-crunchy-data-pgbench
        imagePullPolicy: IfNotPresent
        name: pgbench
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /pgconf
          name: pgconf-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: pgconf-volume