# Global required kustomize configuration
nameReference:
- fieldSpecs:
  - kind: SASDeployment
    path: spec/license/secretKeyRef/name
  - kind: SASDeployment
    path: spec/clientCertificate/secretKeyRef/name
  - kind: SASDeployment
    path: spec/caCertificate/secretKeyRef/name
  kind: Secret
  version: v1
- fieldSpecs:
  - kind: ESPConfig
    path: spec/projectTemplate/deployment/spec/template/spec/containers/env/valueFrom/secretKeyRef/name
  - kind: ESPConfig
    path: spec/projectTemplate/deployment/spec/template/spec/imagePullSecrets/name
  kind: Secret
  version: v1