apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: annotations-transformer
annotations:
  sas.com/component-name: sas-business-rules-services
fieldSpecs:
- path: metadata/annotations
  create: true