# Transformers for deployment operator
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-transformer-sas-deployment-operator
patch: |-
  # name: MUST BE PROVIDED BY USER AND UNIQUE IN CLUSTER. DEFAULT VALUE IS 'sas-deployment-operator'
  - op: replace
    path: /metadata/name
    value:
      sas-deployment-operator
  # namespace: MUST BE PROVIDED BY USER. DEFAULT VALUE IS 'default'
  - op: add
    path: /subjects/0/namespace
    value:
      default
target:
  annotationSelector: sas.com/component-name=sas-deployment-operator
  kind: ClusterRoleBinding
