# This block of code is for specifying the number of workers in an MPP
# deployment. Do not use this block for SMP deployments. The default value is 2
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-manage-workers
patch: |-
   - op: replace
     path: /spec/workers
     value:
       {{ NUMBER-OF-WORKERS }}
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
