###############################################################################
# Kustomize patch to add external SSSD secret in CAS deployment.
# See README.md for more information.
###############################################################################
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-sssd-example
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/volumes/-
    value:
      name: sssd-config
      secret:
        secretName: sas-sssd-config
        defaultMode: 420
        items:
        - key: SSSD_CONF
          mode: 384
          path: sssd.conf

  - op: add
    path: /spec/controllerTemplate/spec/containers/3/volumeMounts/-
    value:
      name: sssd-config
      mountPath: /sssd
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
