
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: sas-consul-server
    sas.com/admin: namespace
  name: sas-consul-server
spec:
  ports:
  - name: server
    port: 8300
    targetPort: server
  - name: serflan-tcp
    port: 8301
    protocol: TCP
    targetPort: serflan-tcp
  - name: serflan-udp
    port: 8301
    protocol: UDP
    targetPort: serflan-udp
  - name: http
    port: 8500
    targetPort: http
  selector:
    app.kubernetes.io/name: sas-consul-server
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: sas-consul-server-internal
    sas.com/admin: namespace
  name: sas-consul-server-internal
spec:
  ports:
  - name: server-internal
    port: 8300
    targetPort: server
  - name: serflan-tcp-internal
    port: 8301
    protocol: TCP
    targetPort: serflan-tcp
  - name: serflan-udp-internal
    port: 8301
    protocol: UDP
    targetPort: serflan-udp
  - name: http-internal
    port: 8500
    targetPort: http
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: sas-consul-server
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/kustomize-base: base
    sidecar.istio.io/proxyCPU: 15m
    sidecar.istio.io/proxyMemory: 115Mi
  labels:
    app.kubernetes.io/name: sas-consul-server
    sas.com/admin: namespace
    workload.sas.com/class: stateful
  name: sas-consul-server
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-consul-server
  serviceName: sas-consul-server-internal
  template:
    metadata:
      annotations:
        sas.com/certificate-file-format: pem
        sas.com/kustomize-base: base
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        sidecar.istio.io/proxyCPU: 15m
        sidecar.istio.io/proxyMemory: 115Mi
        traffic.sidecar.istio.io/excludeInboundPorts: "8301"
      labels:
        app: sas-consul-server
        app.kubernetes.io/name: sas-consul-server
        workload.sas.com/class: stateful
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: In
                values:
                - stateful
            weight: 100
          - preference:
              matchExpressions:
              - key: workload.sas.com/class
                operator: NotIn
                values:
                - compute
                - cas
                - stateless
                - connect
            weight: 50
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: NotIn
                values:
                - system
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - sas-consul-server
              topologyKey: kubernetes.io/hostname
            weight: 100
      automountServiceAccountToken: false
      containers:
      - env:
        - name: CONSUL_BOOTSTRAP_EXPECT
          value: "3"
        - name: CONSUL_CLIENT_ADDRESS
          value: 0.0.0.0
        - name: CONSUL_DATACENTER_NAME
          value: viya
        envFrom:
        - configMapRef:
            name: sas-shared-config
        - secretRef:
            name: sas-consul-client
        - secretRef:
            name: sas-consul-management
        image: sas-consul-server
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /opt/sas/viya/home/bin/consul leave
        name: sas-consul-server
        ports:
        - containerPort: 8300
          name: server
          protocol: TCP
        - containerPort: 8301
          name: serflan-tcp
          protocol: TCP
        - containerPort: 8301
          name: serflan-udp
          protocol: UDP
        - containerPort: 8500
          name: http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - if [ -z ${SAS_CERTIFICATE_FILE} ]; then reply=$(curl -s -L -o /dev/null
              -w %{http_code} http://localhost:${SAS_CONSUL_SERVER_SERVICE_PORT_HTTP}/);
              else reply=$(curl -s -L -o /dev/null -w %{http_code} --cacert ${SAS_TRUSTED_CA_CERTIFICATES_PEM_FILE}
              https://localhost:${SAS_CONSUL_SERVER_SERVICE_PORT_HTTP}/); fi; if [
              $reply -ne 200 ]; then exit 1; fi; test -f /tmp/healthy;
          initialDelaySeconds: 45
          periodSeconds: 30
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 150Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /opt/sas/viya/config/etc/consul.d
          name: tmp-volume
          subPath: consul.d
        - mountPath: /opt/sas/viya/config/etc/consul.d/default
          name: sitedefault-vol
        - mountPath: /consul/data
          name: sas-viya-consul-data-volume
        - mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/tokens/consul/default
          name: tmp-volume
          subPath: consul-tokens
        - mountPath: /opt/sas/viya/config/tmp/sas-consul
          name: tmp-volume
          subPath: sas-consul
        - mountPath: /tmp
          name: tmp-volume
          subPath: tmp
      imagePullSecrets: []
      initContainers:
      - env:
        - name: SAS_KEYS_SECRET_NAME
          value: sas-consul-client
        - name: SAS_KEYS_KEY_NAMES
          value: CONSUL_HTTP_TOKEN
        - name: SAS_SECURITY_ARTIFACTS_DIR
          value: /security
        - name: SAS_CERTFRAME_TOKEN_DIR
          value: /certframe-token
        image: sas-certframe
        name: sas-certframe-client-token-generator
        volumeMounts:
        - mountPath: /security
          name: security
        - mountPath: /certframe-token
          name: certframe-token
      - env:
        - name: SAS_KEYS_SECRET_NAME
          value: sas-consul-management
        - name: SAS_KEYS_KEY_NAMES
          value: CONSUL_MANAGEMENT_TOKEN CONSUL_TOKENS_ENCRYPTION
        - name: SAS_KEYS_KEY_TYPES
          value: uuid base64
        - name: SAS_SECURITY_ARTIFACTS_DIR
          value: /security
        - name: SAS_CERTFRAME_TOKEN_DIR
          value: /certframe-token
        image: sas-certframe
        name: sas-certframe-management-token-generator
        volumeMounts:
        - mountPath: /security
          name: security
        - mountPath: /certframe-token
          name: certframe-token
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      terminationGracePeriodSeconds: 600
      tolerations:
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateful
      - effect: NoSchedule
        key: workload.sas.com/class
        operator: Equal
        value: stateless
      volumes:
      - configMap:
          items:
          - key: SITEDEFAULT_CONF
            mode: 438
            path: sitedefault.yml
          name: sas-consul-config
        name: sitedefault-vol
      - emptyDir: {}
        name: tmp-volume
      - emptyDir: {}
        name: security
      - name: certframe-token
        secret:
          secretName: sas-certframe-token
  volumeClaimTemplates:
  - metadata:
      name: sas-viya-consul-data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    sas.com/ha-class: decentralized
    sas.com/kustomize-base: decentralized
  name: sas-consul-server
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: sas-consul-server
