nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/controllerTemplate/spec/containers/envFrom/configMapRef/name
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/initContainers/envFrom/configMapRef/name
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/containers/env/valueFrom/configMapKeyRef/name
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/initContainers/env/valueFrom/configMapKeyRef/name
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/volumes/configMap/name
    kind: CASDeployment
- kind: Secret
  version: v1
  fieldSpecs:
  - path: spec/controllerTemplate/spec/containers/env/valueFrom/secretKeyRef/name
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/initContainers/env/valueFrom/secretKeyRef/name
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/volumes/secret/secretName
    kind: CASDeployment
- kind: Secret
  version: v1
  fieldSpecs:
  - path: spec/controllerTemplate/spec/imagePullSecrets/name
    kind: CASDeployment
varReference:
  - path: spec/ingressTemplate/spec/rules/host
    kind: CASDeployment
  - path: spec/ingressTemplate/spec/tls/hosts
    kind: CASDeployment
  - path: metadata/name
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/containers/env/value
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/containers/volumeMounts/name
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/volumes/persistentVolumeClaim/claimName
    kind: CASDeployment
  - path: spec/controllerTemplate/spec/volumes/name
    kind: CASDeployment
  - path: metadata/name
    kind: PersistentVolumeClaim
  - path: "metadata/labels/sas.com~1cas-instance"
    kind: PersistentVolumeClaim
