apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: annotations-transformer
annotations:
  sas.com/component-name: sas-text-cas-data-management
fieldSpecs:
- path: metadata/annotations
  create: true