apiVersion: orchestration.sas.com/v1
kind: LifecycleOperation
metadata:
  name: deploy
spec:
  args:
  - name: namespace
  - name: manifest
  - default: 60s
    name: timeout
  steps:
  - args:
    - apply
    - --selector
    - sas.com/admin=cluster-wide
    - --namespace
    - $namespace
    - -f
    - $manifest
    cmd: kubectl
  - args:
    - wait
    - --for
    - condition=established
    - --timeout
    - $timeout
    - --selector
    - sas.com/admin=cluster-wide
    - crd
    cmd: kubectl
  - args:
    - apply
    - --selector
    - sas.com/admin=cluster-local
    - --prune
    - --namespace
    - $namespace
    - -f
    - $manifest
    cmd: kubectl
  - args:
    - apply
    - --selector
    - sas.com/admin=namespace
    - --prune
    - --namespace
    - $namespace
    - -f
    - $manifest
    cmd: kubectl
  - args:
    - apply
    - --selector
    - sas.com/admin=namespace
    - --prune
    - --prune-whitelist
    - networking.istio.io/v1alpha3/DestinationRule
    - --prune-whitelist
    - networking.istio.io/v1alpha3/VirtualService
    - --namespace
    - $namespace
    - -f
    - $manifest
    cmd: kubectl
    when: .ClusterHasGroup "networking.istio.io"
