apiVersion: orchestration.sas.com/v2beta2
kind: LifecycleOperation
metadata:
  name: scale-to-zero
spec:
  args:
  - name: namespace
  - default: 60s
    name: timeout
  steps:
  - args:
    - scale
    - --namespace
    - $namespace
    - deployments
    - --replicas
    - "0"
    - --selector
    - sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
    cmd: kubectl
  - args:
    - scale
    - --namespace
    - $namespace
    - statefulsets
    - --replicas
    - "0"
    - --selector
    - sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
    cmd: kubectl
  - args:
    - patch
    - --namespace
    - $namespace
    - cronjobs
    - $resource.Name
    - --patch
    - '{"spec":{"suspend":true}}'
    cmd: kubectl
    withClusterResources:
      group: batch
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: cronjobs
      version: v1beta1
  - args:
    - patch
    - --namespace
    - $namespace
    - casdeployments
    - $resource.Name
    - --type
    - json
    - --patch
    - '[{"op":"replace", "path": "/spec/shutdown", "value":true}]'
    cmd: kubectl
    when: .ClusterHasGroup "viya.sas.com"
    withClusterResources:
      group: viya.sas.com
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: casdeployments
      version: v1alpha1
  - args:
    - patch
    - --namespace
    - $namespace
    - daemonsets
    - $resource.Name
    - --patch
    - '{"spec":{"template":{"spec":{"nodeSelector":{"sas.com/scale-class":"zero"}}}}}'
    cmd: kubectl
    withClusterResources:
      group: apps
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: daemonsets
      version: v1
  - args:
    - patch
    - --namespace
    - $namespace
    - pgclusters
    - $resource.Name
    - --type
    - json
    - --patch
    - '[{"op":"replace", "path": "/spec/shutdown", "value":true}]'
    cmd: kubectl
    when: .ClusterHasGroup "crunchydata.com"
    withClusterResources:
      group: crunchydata.com
      labelSelector: sas.com/deployment=sas-viya,!sas.com/zero-scale-phase
      namespace: $namespace
      resource: pgclusters
      version: v1
  - args:
    - wait
    - --namespace
    - $namespace
    - --for
    - delete
    - pod
    - --selector
    - app.kubernetes.io/managed-by=sas-cas-operator
    - --timeout
    - $timeout
    cmd: kubectl
  - args:
    - wait
    - --namespace
    - $namespace
    - --for
    - delete
    - pod
    - --selector
    - vendor=crunchydata,role
    - --timeout
    - $timeout
    cmd: kubectl
  - args:
    - scale
    - --namespace
    - $namespace
    - deployments
    - --replicas
    - "0"
    - --selector
    - sas.com/deployment=sas-viya,sas.com/zero-scale-phase=1
    cmd: kubectl
