---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-set-qkb-defaults
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/env/-
    value:
      name: CASCFG_DQSETUPLOC
      value: "QKB NAME"
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/env/-
    value:
      name: CASCFG_DQLOCALE
      value: "ENUSA"
target:
  kind: CASDeployment
  name: default

