
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sas-viya-backuprunner

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sas-viya-backuprunner
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - podtemplates
  verbs:
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
  - list
- apiGroups:
  - viya.sas.com
  resources:
  - casdeployments
  verbs:
  - get
  - delete
  - list
  - deletecollection
- apiGroups:
  - iot.sas.com
  resources:
  - espservers
  verbs:
  - get
  - delete
  - list
  - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sas-viya-backuprunner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sas-viya-backuprunner
subjects:
- kind: ServiceAccount
  name: sas-viya-backuprunner

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: sas-scheduled-backup-job
    sas.com/backup-job-type: "scheduled-backup"
    workload.sas.com/class: stateless
  annotations:
    sas.com/certificate-file-format: pem
  name: sas-scheduled-backup-job
spec:
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: sas-scheduled-backup-job
        sas.com/backup-job-type: "scheduled-backup"
        sas.com/admin: namespace
        workload.sas.com/class: stateless
    spec:
      template:
        metadata:
          annotations:
            sas.com/certificate-file-format: pem
            seccomp.security.alpha.kubernetes.io/pod: runtime/default
          labels:
            workload.sas.com/class: stateless
        spec:
          securityContext:
            runAsNonRoot: true
            supplementalGroups: []
            sysctls: []
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: In
                    values:
                    - stateless
                weight: 100
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: NotIn
                    values:
                    - compute
                    - cas
                    - stateful
                weight: 50
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.azure.com/mode
                    operator: NotIn
                    values:
                    - system
          containers:
          - envFrom:
            - configMapRef:
                name: sas-go-config
            - configMapRef:
                name: sas-shared-config
            - configMapRef:
                name: sas-java-config
            - configMapRef:
                name: sas-backup-job-parameters
            - secretRef:
                name: sas-consul-client
            env:
            - name: BACKUP_MOUNT_LOCATION
              value: /sasviyabackup
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['job-name']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            image: sas-backup-job
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: backup
              mountPath: /sasviyabackup
            securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              readOnlyRootFilesystem: true
              capabilities: 
                drop:
                - ALL
            name: sas-backup-job
          - env:
            - name: BACKUP_AGENT_TYPE
              value: REMOTE
            - name: BACKUP_MOUNT_LOCATION
              value: /sasviyabackup
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['job-name']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            envFrom:
            - configMapRef:
                name: sas-go-config
            - configMapRef:
                name: sas-shared-config
            - configMapRef:
                name: sas-java-config
            - configMapRef:
                name: sas-backup-agent-parameters
            - secretRef:
                name: sas-consul-client
            image: sas-backup-agent
            imagePullPolicy: IfNotPresent
            name: sas-backup-agent
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - name: backup
              mountPath: /sasviyabackup
            securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              readOnlyRootFilesystem: true
              capabilities: 
                drop:
                - ALL
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: sas-common-backup-data
          restartPolicy: Never
          serviceAccountName: sas-viya-backuprunner
          tolerations:
          - effect: NoSchedule
            key: workload.sas.com/class
            operator: Equal
            value: stateful
          - effect: NoSchedule
            key: workload.sas.com/class
            operator: Equal
            value: stateless
  schedule: 0 1 * * 0
  successfulJobsHistoryLimit: 100
  failedJobsHistoryLimit: 100
  suspend: false


---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    sas.com/certificate-file-format: pem
  labels:
    app.kubernetes.io/name: sas-backup-purge-job
    sas.com/backup-job-type: "purge-backup"
    workload.sas.com/class: stateless
  name: sas-backup-purge-job
spec:
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: sas-backup-purge-job
        sas.com/backup-job-type: "purge-backup"
        sas.com/admin: namespace
        workload.sas.com/class: stateless
    spec:
      template:
        metadata:
          annotations:
            sas.com/certificate-file-format: pem
            seccomp.security.alpha.kubernetes.io/pod: runtime/default
          labels:
            workload.sas.com/class: stateless
        spec:
          securityContext:
            runAsNonRoot: true
            supplementalGroups: []
            sysctls: []
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: In
                    values:
                    - stateless
                weight: 100
              - preference:
                  matchExpressions:
                  - key: workload.sas.com/class
                    operator: NotIn
                    values:
                    - compute
                    - cas
                    - stateful
                weight: 50
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.azure.com/mode
                    operator: NotIn
                    values:
                    - system
          containers:
          - envFrom:
            - configMapRef:
                name: sas-go-config
            - configMapRef:
                name: sas-shared-config
            - configMapRef:
                name: sas-java-config
            - configMapRef:
                name: sas-backup-job-parameters
            - secretRef:
                name: sas-consul-client
            env:
            - name: BACKUP_MOUNT_LOCATION
              value: /sasviyabackup
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['job-name']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JOB_TYPE
              value: purge
            image: sas-backup-job
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: backup
              mountPath: /sasviyabackup
            securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              readOnlyRootFilesystem: true
              capabilities: 
                drop:
                - ALL
            name: sas-backup-purge-job
          - env:
            - name: BACKUP_AGENT_TYPE
              value: REMOTE
            - name: BACKUP_MOUNT_LOCATION
              value: /sasviyabackup
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['job-name']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            envFrom:
            - configMapRef:
                name: sas-go-config
            - configMapRef:
                name: sas-shared-config
            - configMapRef:
                name: sas-java-config
            - configMapRef:
                name: sas-backup-agent-parameters
            - secretRef:
                name: sas-consul-client
            image: sas-backup-agent
            imagePullPolicy: IfNotPresent
            name: sas-backup-agent
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - name: backup
              mountPath: /sasviyabackup
            securityContext:
              allowPrivilegeEscalation: false
              privileged: false
              readOnlyRootFilesystem: true
              capabilities: 
                drop:
                - ALL
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: sas-common-backup-data
          restartPolicy: Never
          serviceAccountName: sas-viya-backuprunner
          tolerations:
          - effect: NoSchedule
            key: workload.sas.com/class
            operator: Equal
            value: stateful
          - effect: NoSchedule
            key: workload.sas.com/class
            operator: Equal
            value: stateless
  schedule: 15 0 1/1 * ?
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  suspend: false


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    sas.com/backup-role: "storage"
  name: sas-common-backup-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
