apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-sssd-sidecar
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/containers/-
    value:
      env:
      - name: SAS_K8S_DEPLOYMENT_NAME
        value: "sas-sssd-server"
      image: sas-sssd-server
      name: sssd
      lifecycle:
        preStop:
          exec:
            command: ["bash", "-c", "kill -SIGKILL $(ps -Af | grep '/opt/sas/viya/home/bin/consul-template'  | grep -v grep | awk '{print $2}')", "kill -SIGKILL $(ps -Af | grep '/sbin/sssd'  | grep -v grep | awk '{print $2}')"]
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 100m
      envFrom:
      - configMapRef:
          name: sas-shared-config
      - configMapRef:
          name: sas-java-config
      - secretRef:
          name: sas-consul-client
      volumeMounts:
       - mountPath: /var/lib/sss
         name: sss
    volumes:
    - emptyDir: {}
      name: sss

  - op: add
    path: /metadata/annotations/sas.com~1pod-uses-sssd
    value: "true"
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-container-sssd-mounts
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/volumes/-
    value:
      name: sss
      emptyDir: {}
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
    value:
      name: sss
      mountPath: /var/lib/sss
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
