apiVersion: viya.sas.com/v1alpha1
kind: CASDeployment
metadata:
  annotations:
    sas.com/sas-access-config: "true"
    sas.com/config-init-mode: "initcontainer"
  labels:
    app: sas-cas-operator
    app.kubernetes.io/instance: "$(CAS_INSTANCE)"
    app.kubernetes.io/name: "cas"
    app.kubernetes.io/managed-by: sas-cas-operator
    sas.com/admin: "namespace"
    workload.sas.com/class: cas
    sas.com/cas-server-default: "true"
  name: "$(CAS_INSTANCE)"
spec:
  controllerTemplate:
    spec:
      tolerations:
      - key: "workload.sas.com/class"
        operator: "Equal"
        value: "cas"
        effect: "NoSchedule"
      initContainers:
      - image: sas-config-init
        name: sas-config-init
        env: []
        envFrom:
          - configMapRef:
              name: sas-go-config
          - configMapRef:
              name: sas-shared-config
          - secretRef:
              name: sas-consul-client
        volumeMounts:
          - mountPath: /cas/config/
            name: cas-default-config-volume
        resources:
          limits:
            memory: 2Gi
            cpu: 1
      containers:
      - name: cas  # required name for the CAS container
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /internal/state
            port: 8777
          initialDelaySeconds: 5
          periodSeconds: 10
        #args:  # change the command so we can manually run the entrypoint script and debug cas
          #- while true; do sleep 30; done;
        #command:
          #- /bin/bash
          #- -c
          #- --
        env:
        - name: SAS_LICENSE
          valueFrom:
            secretKeyRef:
              key: SAS_LICENSE
              name: sas-cas-license
        - name: CONSUL_HTTP_ADDR
          value: http://localhost:8500
        envFrom:
        - configMapRef:
            name: sas-shared-config
        - configMapRef:
            name: sas-java-config
        - configMapRef:
            name: sas-access-config
        - configMapRef:
            name: sas-cas-config
        - configMapRef:
            name: sas-deployment-metadata
        - secretRef:
            name: sas-consul-client
        image: sas-cas-server
        resources:
          requests:
            memory: 2Gi
            cpu: 250m
        volumeMounts:
        - name: cas-default-permstore-volume
          mountPath: /cas/permstore
        - name: cas-default-data-volume
          mountPath: /cas/data
        - name: cas-default-cache-volume
          mountPath: /cas/cache
        - name: cas-default-config-volume
          mountPath: /cas/config
        - name: cas-tmp-volume
          mountPath: /tmp
          subPath: tmp
        - name: cas-license-volume
          mountPath: /cas/license
      imagePullSecrets:
      - name: sas-image-pull-secrets
      serviceAccountName: sas-cas-server
      volumes:
      - name: cas-default-permstore-volume
        persistentVolumeClaim:
          claimName: cas-$(CAS_INSTANCE)-permstore
      - name: cas-default-data-volume
        persistentVolumeClaim:
          claimName: cas-$(CAS_INSTANCE)-data
      - name: cas-default-cache-volume
        emptyDir: {}
      - name: cas-default-config-volume
        emptyDir: {}
      - name: cas-tmp-volume
        emptyDir: {}
      - name: cas-license-volume
        secret:
          secretName: sas-cas-license
          items:
          - key: SAS_LICENSE
            path: license.sas
  workers: 0
  backupControllers: 0
  workerTemplate:
    #podSpec - optional worker template
  publishHTTPIngress: true
  ingressTemplate:
    spec:
      rules:
      - host: $(INGRESS_HOST)
    metadata:
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 2048m
        nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      labels: {}
