apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: cas-input
literals:
- CAS_INSTANCE=default
---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: sas-cas-config
literals:
- CASCLOUDNATIVE=1
