# This block of code is for adding a GPU sidecar
# to the CAS container.
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-gpud-sidecar
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/containers/-
    value:
      env:
      - name: SASGPUD_LOG_TYPE
        value: info
      volumeMounts:
      - mountPath: /var/tmp/sasgpud
        name: sasgpud-volume
      image: sas-gpu-server
      name: sasgpud

  - op: add
    path: /metadata/annotations/sas.com~1pod-uses-gpud
    value: "true"
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-shared-process-namespace
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/shareProcessNamespace
    value:
      true
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
---
# Add additional mount
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-sasgpud-mount
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/volumes/-
    value:
      name: sasgpud-volume
      emptyDir: {}
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
    value:
      name: sasgpud-volume
      mountPath: /var/tmp/sasgpud
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
---
# nvdidia gpu patch
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-nvidia-vars
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/env/-
    value:
      name: NVIDIA_DRIVER_CAPABILITIES
      value: all
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/env/-
    value:
      name: NVIDIA_REQUIRE_CUDA
      value: "brand=quadro brand=tesla arch=pascal arch=volta arch=turing driver>=410.48"
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-modify-gpu
patch: |-
   - op: add
     path: "/spec/controllerTemplate/spec/containers/0/resources/requests/nvidia.com~1gpu"
     value:
       1
   - op: add
     path: /spec/controllerTemplate/spec/containers/0/resources/limits
     value:
       nvidia.com/gpu: 1
target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
#---
# Optional lib64 mount
#apiVersion: builtin
#kind: PatchTransformer
#metadata:
#  name: cas-lib64-mount
#patch: |-
#  - op: add
#    path: /spec/controllerTemplate/spec/volumes/-
#    value:
#     name: usr-lib64
#     hostPath:
#       path: /usr/lib64/libcuda.so
#  - op: add
#    path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
#    value:
#      name: usr-lib64
#      mountPath: /usr/lib64/libcuda.so
#target:
#  group: viya.sas.com
#  kind: CASDeployment
#  name: .*
#  version: v1alpha1
