---
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: sas-deployment-operator-annotations-transformer
annotations:
  sas.com/component-name: sas-deployment-operator
fieldSpecs:
  - path: metadata/annotations
    create: true
  - path: spec/template/metadata/annotations
    create: true
    kind: Deployment

---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: sas-deployment-operator-label-transformer
labels:
  app.kubernetes.io/name: sas-deployment-operator
  sas.com/admin: cluster-wide
  sas.com/deployment: sas-viya
fieldSpecs:
  - path: metadata/labels
    create: true
  - path: spec/selector
    create: true
    version: v1
    kind: Service
  - path: spec/selector/matchLabels
    create: true
    kind: Deployment
  - path: spec/template/metadata/labels
    create: true
    kind: Deployment
  - path: spec/template/spec/affinity/podAffinity/preferredDuringSchedulingIgnoredDuringExecution/podAffinityTerm/labelSelector/matchLabels
    create: false
    group: apps
    kind: Deployment
  - path: spec/template/spec/affinity/podAffinity/requiredDuringSchedulingIgnoredDuringExecution/labelSelector/matchLabels
    create: false
    group: apps
    kind: Deployment
  - path: spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/podAffinityTerm/labelSelector/matchLabels
    create: false
    group: apps
    kind: Deployment
  - path: spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution/labelSelector/matchLabels
    create: false
    group: apps
    kind: Deployment

---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-deployment-operator-role-namespace-remover
patch: |-
  - op: remove
    path: /metadata/namespace
target:
  kind: Role
