# This block of code is for setting up Kerberos support
# for a compute session
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-krb5-proxy-sidecar
patch: |-
  - op: add
    path: /metadata/annotations/launcher.sas.com~1jobContainerName
    value:
      sas-programming-environment
  - op: add
    path: /template/spec/containers/-
    value:
      env:
      - name: SAS_K8S_DEPLOYMENT_NAME
        value: "sas-krb5-proxy"
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      image: sas-krb5-proxy
      name: sas-krb5-proxy
      securityContext:
        runAsGroup: 1001
        runAsUser: 1001
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: false
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 75m
          memory: 64Mi
      volumeMounts:
      - mountPath: /opt/kerberos
        name: sas-kerberos-secrets-volume
        readOnly: true
      envFrom:
      - configMapRef:
          name: sas-servers-kerberos-config
      - configMapRef:
          name: sas-go-config
      - configMapRef:
          name: sas-shared-config
target:
  name: sas-compute-job-config
  version: v1
  kind: PodTemplate
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-krb5-proxy-secrets
patch: |-
  - op: add
    path: /template/spec/volumes/-
    value:
      name: sas-kerberos-secrets-volume
      secret:
        secretName: sas-servers-kerberos-secrets
  - op: add
    path: /template/spec/containers/0/volumeMounts/-
    value:
      name: sas-kerberos-secrets-volume
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
      readOnly: true
target:
  name: sas-compute-job-config
  version: v1
  kind: PodTemplate
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-kerberos-enable
patch: |-
  - op: add
    path: /template/spec/containers/0/env/-
    value:
      name: SAS_KERBEROS_ENABLED
      value: "true"
target:
  name: sas-compute-job-config
  version: v1
  kind: PodTemplate
---